In [1]:
import numpy as np 

# create array using numpy 
## create a D1 array 

In [ ]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

print(type(arr1))
print(arr1.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape((1,5)) # 1 row and 5 columns 

array([[1, 2, 3, 4, 5]])

In [8]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
# 2D array 
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])  # 2 rows # 5 columns 
print(arr2)
arr2.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [22]:
P = np.arange(0,10,2).reshape(5,1) # 5 rows 1 columns 
print(P.shape)
print(P)

(5, 1)
[[0]
 [2]
 [4]
 [6]
 [8]]


In [29]:
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
# identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 
arr3 = np.array([[1,2,3],[4,5,6]])
print("Array :\n" ,arr3  )
print("Shape :", arr3.shape) #output : 2 "(2,3) 2rows 3 columns "
print("Number of dimensions:" ,arr3.ndim) # output "2" 2D array 
print("Size (number of elmernts) :", arr3.size) #out put 6 

print("DAtae type:" ,arr3.dtype) # output :int64 (may vary based on platform)
print("item size(in bytes):",arr3.itemsize) # out put: 8 (may vary bassed on )

Array :
 [[1 2 3]
 [4 5 6]]
Shape : (2, 3)
Number of dimensions: 2
Size (number of elmernts) : 6
DAtae type: int64
item size(in bytes): 8


In [37]:
#Numpy Vectorized opration 

arr = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Elemnet Wise addtion 
print("Addtion :",arr+arr2)
# Elemnet Wise Substractoin 
print("Sub :", arr-arr2)
# mult Wise mult 
print("mult:",arr*arr2)

Addtion : [11 22 33 44 55]
Sub : [ -9 -18 -27 -36 -45]
mult: [ 10  40  90 160 250]


In [42]:
## Universal Function 
arr = np.array([1,2,3,4,5,6])
## Squear root 
print(np.sqrt(arr))
# Exponential
print(np.exp(arr))
## sine 
print(np.sin(arr))
## 
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [44]:
## array slicing and indexing
# 

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)  
arr[0][0]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


np.int64(1)

In [47]:
### statistical concepts -- Normalization 
## too have a mean of 0 and standar deviation of 1
data = np.array([1,2,3,4])
mean = np.mean(data)

std_div = np.std(data)
normalized_data = (data-mean) / std_div
print(normalized_data)

[-1.34164079 -0.4472136   0.4472136   1.34164079]


In [50]:
data1 = np.array([1,2,3,4,5,6,7,8,9,10])
mean = np.mean(data1)

medin = np.median(data1)

std_dev = np.std(data1)
variance = np.var(data,ddof =1)

print("mean :" ,mean)

print("median :" ,medin)

print("stdander Deviation :" ,std_dev)

print("variance :", variance)


mean : 5.5
median : 5.5
stdander Deviation : 2.8722813232690143
variance : 1.6666666666666667


In [53]:
# Logical operation 
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data>5)
print(data[data>5])
print(data[(data >=5) & (data<=8)])


[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
